# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
