# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160526_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
